# Generated by Django 5.2.17 on 2026-08-23 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0005_round_rounditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_number",
                    models.PositiveIntegerField(editable=False, unique=True),
                ),
                ("subtotal", models.PositiveIntegerField()),
                ("tax_enabled", models.BooleanField(default=False)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("tax_amount", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField()),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="pos.table",
                    ),
                ),
            ],
            options={
                "ordering": ["-bill_number"],
            },
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=150)),
                ("category_name", models.CharField(max_length=100)),
                ("category_type", models.CharField(max_length=5)),
                ("unit_price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.PositiveIntegerField()),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pos.bill",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="pos.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
