# Generated by Django 5.2.17 on 2026-08-23 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0007_setting_cancelledorder_cancelleditem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
