# Generated by Django 5.2.17 on 2026-08-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0008_alter_round_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[("PAID", "Paid"), ("CANCELLED", "Cancelled")],
                default="PAID",
                max_length=20,
            ),
        ),
    ]
