# Generated by Django 5.2.17 on 2026-08-23 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0009_bill_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="bill_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="bill_number",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
