# Generated by Django 5.2.17 on 2026-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0010_bill_bill_date_alter_bill_bill_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_number",
            field=models.BigIntegerField(editable=False),
        ),
    ]
